title: "JohnBSE — Laravel Projects Portfolio"
baseurl: "/personal-portfolio"
url: "https://johnbse.github.io"
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /:collection/:name/

description: "A portfolio of Laravel projects by JOHN BSE"
